[이준호] 레포 초기 셋팅
wecode-bootcamp-korea/49-1st-Team8-backend pull request #1
Opened 2023-09-11 08:05 UTC by yummyicecream

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, <br> 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.

- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?

  (예시) 고객의 유입과 전환을 책임지는 회원 기능에서, 유저의 이탈을 방지하기 위해 input 창 바로 아래에서 실시간으로 적색의 경고 메세지를 전달 받습니다.

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?

  (예시) 유저는 실시간으로 스스로 오기입한 내용을 확인할 수 있기 때문에 잘못 계정 정보를 작성함으로써 발생될 수 있는 변수를 최소화할 수 있습니다. 이는 곧 유저 전환의 허들을 낮추어 줄 수 있습니다.

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 상세 내역을 적어주세요.

(예시) 로그인 기능 추가

- (예시) email입력 `@`필요,password에 숫자로 8자이상 유효성 검사 추가
- (예시) 유효성 검사 통과시 버튼 컬러 변경 및 버튼 활성화

<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. 
<br />

- (drag & drop 또는 첨부파일 추가)

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

- (예시) 새로운 배열메서드 filter를 쓸 수 있게됐습니다.
- (예시) 상수데이터와 map 메서드로 반복되는 UI를 그릴 수 있게 됐습니다.
- (예시) fetch함수를 어떻게 쓰는지 알게됐습니다.
- (예시) 계산된 속성명 (computed property)을 쓰긴했는데 어떻게 돌아가는지 이해가 잘 안되서
  블로그에 정리해봐야겠습니다.
- (예시) 화살표 함수(arrow-function) 어떤 코드를 언제 생략할 수있는지 완벽 이해했습니다.
- (예시) 구조분해할당(Destructuring assignment)을 써보니 가독성도, 유지보수도 편할것같습니다.
  <br />

2023-09-11 08:13 UTC, kyeongraekim requested changes

2023-09-11 08:13 UTC, kyeongraekim commented on .env.sample
> +DB_PASSWORD=248464
-샘플 파일로 올려주시는 코드에는 보다 plain 한 용어로 기입이 되어 있으셔야 합니다. 
- 실제 비밀번호로 쓰임받을 법한 숫자내용은 제거하여 올려주세요!

2023-09-11 08:13 UTC, kyeongraekim commented on .env.sample
> +DB_NAME=wereads
- 해당 데이터 베이스 명칭도 가칭의 데이터베이스 명칭이 기입되어있어야 합니다.
- 샘플 파일은 말 그대로 동료 개발자가 자신의 초기환경 세팅 시 참고를 해야하는 명칭의 가칭임으로, 실제 데이터 값과 같은 value가 기입되지 않게 수정하여주세요.

2023-09-11 08:13 UTC, kyeongraekim commented on db/migrations/20230911075113_create_users_table.sql
> +  email VARCHAR(200) NOT NULL,
- 이메일은 보통 unique 한 값 설정을 통해, 중복의 데이터 기입을 막습니다.
- 해당 내용에 unique 속성을 추가하여주세요!

2023-09-11 08:13 UTC, kyeongraekim commented on db/migrations/20230911075226_create_thread_likes_table.sql
> +
- 대부분의 소셜미디어 기능에는 좋아요 / 좋아요 해제 등 동일 사용자의 동일 게시글 좋아요가 이루어지지 않습니다.?
- 따라서 해당 likes 테이블에 unique contrainst를 (user_id, thread_id) 기준으로 설정하여주세요.

2023-09-11 08:13 UTC, kyeongraekim commented on db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
- 해당 schema.sql 파일은 로컬 데이터 베이스에서만 관리가 이루어져야 하는, 제 3의 개발자와 외부공개를 하지 않는 파일입니다.
- 따라서 .gitignore에 추가하여 해당 내용이 깃헙공간에서 공유되지 않게 수정하여주세요!
- 다음의 명령어를 참고해주세요! 따라주셔야 하는 절차는, 아래의 명령어를 통한 git cache 삭제, git ignore 추가, git add . commit을 이용한 재 푸시입니다.

``` 
git rm -r --cached .

2023-09-11 11:03 UTC, yummyicecream commented on db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
확인완료했습니다.

2023-09-11 11:03 UTC, yummyicecream commented on db/migrations/20230911075226_create_thread_likes_table.sql
> +
확인완료했습니다.

2023-09-11 11:03 UTC, yummyicecream commented on .env.sample
> +DB_NAME=wereads
확인완료했습니다.

2023-09-11 11:03 UTC, yummyicecream commented on .env.sample
> +DB_PASSWORD=248464
확인완료했습니다.

2023-09-12 07:37 UTC, kyeongraekim requested changes

2023-09-12 07:37 UTC, kyeongraekim commented on .env.sample
> +DATABASE_URL = mysql://root:248464@localhost:3306/wereads
- 샘플파일 마지막 부분에 불필요한 데이터베이스 명칭이 노출되어있습니다. 해당 내용을 수정해주세요.

2023-09-12 07:37 UTC, kyeongraekim commented on app.js
> +const userService = require("./src/services/userService.js");
- 초기환경세팅 시점에서 불필요한 Service 변수 및 호출문을 삭제해주세요

2023-09-12 07:37 UTC, kyeongraekim commented on src/services/userService.js
> +const jwt = require("jsonwebtoken");
- 해당내용은 초기세팅 시 불필요한 파일입니다.

2023-09-12 07:37 UTC, kyeongraekim commented on db/migrations/20230911075226_create_thread_likes_table.sql
> +
- 좋아요 기능을 구현할 때에는 주의해야할 점이 있습니다.
- 하나의 사용자가 하나의 게시물에 대해서 좋아요를 할 수 있는 횟수는 단 한 번 이어야 합니다.
- 지금 구조에서는 좋아요를 누를 때마다 아래와 같이 likes 테이블에 계속해서 중복으로 데이터가 저장됩니다.
- 해당 내용의 SQL syntax는 unique constraint () 의 구조를 띄게 되오니 추가 리서치를 통해 올바른 구문을 찾아보세요!
    
    ```sql
    +----+---------+---------+---------------------+
    | id | user_id | post_id | created_at          |
    +----+---------+---------+---------------------+
    |  1 |       1 |       3 | 2022-07-16 14:18:26 |
    |  2 |       1 |       3 | 2022-07-16 14:18:26 |
    |  3 |       1 |       3 | 2022-07-16 14:18:26 |
    |  4 |       1 |       3 | 2022-07-16 14:18:26 |
    |  5 |       1 |       3 | 2022-07-16 14:18:47 |
    |  6 |       1 |       3 | 2022-07-16 14:18:47 |
    +----+---------+---------+---------------------+
    ```
    
- 이를 막기 위해서, likes 테이블에 user_id와 post_id를 기준으로 UNIQUE 제약조건을 추가하는 migration 파일을 추가로 만들어서 올려주세요.

2023-09-12 11:13 UTC, yummyicecream commented on .env.sample
> +DATABASE_URL = mysql://root:248464@localhost:3306/wereads
확인완료했습니다.

2023-09-12 11:13 UTC, yummyicecream commented on app.js
> +const userService = require("./src/services/userService.js");
확인완료했습니다.

2023-09-12 11:14 UTC, yummyicecream commented on src/services/userService.js
> +const jwt = require("jsonwebtoken");
확인완료했습니다.

2023-09-13 03:27 UTC, soheon-lee approved these changes

2023-09-13 03:27 UTC, merged